package GUI;

import main.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;



/**
 * Vytvoøí GUI hry
 * @author matej
 */
public class TownBuildGUI extends JFrame {
    
    public static JFrame okno = new JFrame("Town Build");
    
    public static JPanel buypanel = new JPanel();
    public static JPanel moznosti = new JPanel();
    public static JPanel listveci = new JPanel();
    public static JPanel mrizka = new JPanel();
    public static JLabel hernipole = new JLabel();
    
    public final static ImageIcon obrazeknacitacihopozadi = new ImageIcon("mesto.png");
    public final static ImageIcon obrazekcesty = new ImageIcon("cesta.png");
    public final static ImageIcon obrazekdomu = new ImageIcon("dum.png");
    public final static ImageIcon obrazekuhelnehodolu = new ImageIcon("uhelnydul.png");
    public final static ImageIcon obrazekpozemku = new ImageIcon("trava.png");
    public final static ImageIcon pozemekCesta = new ImageIcon("cesta-pozemek.png");
    public final static ImageIcon pozemekDum = new ImageIcon("dum-pozemek.png");
    public final static ImageIcon pozemekUhelnydul = new ImageIcon("uhelnydul-pozemek.png");
    public static ImageIcon vyslednaIkona;
    
    public static JButton hrat = new JButton("Hrï¿½t");
    public static JButton koupitcestu = new JButton("koupit");
    public static JButton koupitdum = new JButton("koupit");
    public static JButton koupituhelnydul = new JButton("koupit");
    public static JButton obchod = new JButton("Obchod");
    public static JButton mesto = new JButton("Mï¿½sto");
    public static JButton inventar = new JButton("Inventï¿½ï¿½");
    public static JButton nastaveni = new JButton("Nastavenï¿½");
    public static JButton ziskatpenize = new JButton("Zï¿½skat penï¿½ze");
    public static JButton jaksepise = new JButton("Jak se pï¿½e");
    public static JButton place;
    
    public static JButton pozemekx0y0 = new JButton(obrazekpozemku);
    public static JButton pozemekx1y0 = new JButton(obrazekpozemku);
    public static JButton pozemekx2y0 = new JButton(obrazekpozemku);
    public static JButton pozemekx3y0 = new JButton(obrazekpozemku);
    public static JButton pozemekx4y0 = new JButton(obrazekpozemku);
    public static JButton pozemekx5y0 = new JButton(obrazekpozemku);
    public static JButton pozemekx6y0 = new JButton(obrazekpozemku);
    public static JButton pozemekx7y0 = new JButton(obrazekpozemku);
    public static JButton pozemekx8y0 = new JButton(obrazekpozemku);
    public static JButton pozemekx9y0 = new JButton(obrazekpozemku);
    public static JButton pozemekx0y1 = new JButton(obrazekpozemku);
    public static JButton pozemekx1y1 = new JButton(obrazekpozemku);
    public static JButton pozemekx2y1 = new JButton(obrazekpozemku);
    public static JButton pozemekx3y1 = new JButton(obrazekpozemku);
    public static JButton pozemekx4y1 = new JButton(obrazekpozemku);
    public static JButton pozemekx5y1 = new JButton(obrazekpozemku);
    public static JButton pozemekx6y1 = new JButton(obrazekpozemku);
    public static JButton pozemekx7y1 = new JButton(obrazekpozemku);
    public static JButton pozemekx8y1 = new JButton(obrazekpozemku);
    public static JButton pozemekx9y1 = new JButton(obrazekpozemku);
    public static JButton pozemekx0y2 = new JButton(obrazekpozemku);
    public static JButton pozemekx1y2 = new JButton(obrazekpozemku);
    public static JButton pozemekx2y2 = new JButton(obrazekpozemku);
    public static JButton pozemekx3y2 = new JButton(obrazekpozemku);
    public static JButton pozemekx4y2 = new JButton(obrazekpozemku);
    public static JButton pozemekx5y2 = new JButton(obrazekpozemku);
    public static JButton pozemekx6y2 = new JButton(obrazekpozemku);
    public static JButton pozemekx7y2 = new JButton(obrazekpozemku);
    public static JButton pozemekx8y2 = new JButton(obrazekpozemku);
    public static JButton pozemekx9y2 = new JButton(obrazekpozemku);
    public static JButton pozemekx0y3 = new JButton(obrazekpozemku);
    public static JButton pozemekx1y3 = new JButton(obrazekpozemku);
    public static JButton pozemekx2y3 = new JButton(obrazekpozemku);
    public static JButton pozemekx3y3 = new JButton(obrazekpozemku);
    public static JButton pozemekx4y3 = new JButton(obrazekpozemku);
    public static JButton pozemekx5y3 = new JButton(obrazekpozemku);
    public static JButton pozemekx6y3 = new JButton(obrazekpozemku);
    public static JButton pozemekx7y3 = new JButton(obrazekpozemku);
    public static JButton pozemekx8y3 = new JButton(obrazekpozemku);
    public static JButton pozemekx9y3 = new JButton(obrazekpozemku);
    public static JButton pozemekx0y4 = new JButton(obrazekpozemku);
    public static JButton pozemekx1y4 = new JButton(obrazekpozemku);
    public static JButton pozemekx2y4 = new JButton(obrazekpozemku);
    public static JButton pozemekx3y4 = new JButton(obrazekpozemku);
    public static JButton pozemekx4y4 = new JButton(obrazekpozemku);
    public static JButton pozemekx5y4 = new JButton(obrazekpozemku);
    public static JButton pozemekx6y4 = new JButton(obrazekpozemku);
    public static JButton pozemekx7y4 = new JButton(obrazekpozemku);
    public static JButton pozemekx8y4 = new JButton(obrazekpozemku);
    public static JButton pozemekx9y4 = new JButton(obrazekpozemku);
    public static JButton pozemekx0y5 = new JButton(obrazekpozemku);
    public static JButton pozemekx1y5 = new JButton(obrazekpozemku);
    public static JButton pozemekx2y5 = new JButton(obrazekpozemku);
    public static JButton pozemekx3y5 = new JButton(obrazekpozemku);
    public static JButton pozemekx4y5 = new JButton(obrazekpozemku);
    public static JButton pozemekx5y5 = new JButton(obrazekpozemku);
    public static JButton pozemekx6y5 = new JButton(obrazekpozemku);
    public static JButton pozemekx7y5 = new JButton(obrazekpozemku);
    public static JButton pozemekx8y5 = new JButton(obrazekpozemku);
    public static JButton pozemekx9y5 = new JButton(obrazekpozemku);
    public static JButton pozemekx0y6 = new JButton(obrazekpozemku);
    public static JButton pozemekx1y6 = new JButton(obrazekpozemku);
    public static JButton pozemekx2y6 = new JButton(obrazekpozemku);
    public static JButton pozemekx3y6 = new JButton(obrazekpozemku);
    public static JButton pozemekx4y6 = new JButton(obrazekpozemku);
    public static JButton pozemekx5y6 = new JButton(obrazekpozemku);
    public static JButton pozemekx6y6 = new JButton(obrazekpozemku);
    public static JButton pozemekx7y6 = new JButton(obrazekpozemku);
    public static JButton pozemekx8y6 = new JButton(obrazekpozemku);
    public static JButton pozemekx9y6 = new JButton(obrazekpozemku);
    public static JButton pozemekx0y7 = new JButton(obrazekpozemku);
    public static JButton pozemekx1y7 = new JButton(obrazekpozemku);
    public static JButton pozemekx2y7 = new JButton(obrazekpozemku);
    public static JButton pozemekx3y7 = new JButton(obrazekpozemku);
    public static JButton pozemekx4y7 = new JButton(obrazekpozemku);
    public static JButton pozemekx5y7 = new JButton(obrazekpozemku);
    public static JButton pozemekx6y7 = new JButton(obrazekpozemku);
    public static JButton pozemekx7y7 = new JButton(obrazekpozemku);
    public static JButton pozemekx8y7 = new JButton(obrazekpozemku);
    public static JButton pozemekx9y7 = new JButton(obrazekpozemku);
    public static JButton pozemekx0y8 = new JButton(obrazekpozemku);
    public static JButton pozemekx1y8 = new JButton(obrazekpozemku);
    public static JButton pozemekx2y8 = new JButton(obrazekpozemku);
    public static JButton pozemekx3y8 = new JButton(obrazekpozemku);
    public static JButton pozemekx4y8 = new JButton(obrazekpozemku);
    public static JButton pozemekx5y8 = new JButton(obrazekpozemku);
    public static JButton pozemekx6y8 = new JButton(obrazekpozemku);
    public static JButton pozemekx7y8 = new JButton(obrazekpozemku);
    public static JButton pozemekx8y8 = new JButton(obrazekpozemku);
    public static JButton pozemekx9y8 = new JButton(obrazekpozemku);
    public static JButton pozemekx0y9 = new JButton(obrazekpozemku);
    public static JButton pozemekx1y9 = new JButton(obrazekpozemku);
    public static JButton pozemekx2y9 = new JButton(obrazekpozemku);
    public static JButton pozemekx3y9 = new JButton(obrazekpozemku);
    public static JButton pozemekx4y9 = new JButton(obrazekpozemku);
    public static JButton pozemekx5y9 = new JButton(obrazekpozemku);
    public static JButton pozemekx6y9 = new JButton(obrazekpozemku);
    public static JButton pozemekx7y9 = new JButton(obrazekpozemku);
    public static JButton pozemekx8y9 = new JButton(obrazekpozemku);
    public static JButton pozemekx9y9 = new JButton(obrazekpozemku);
    public static JButton pozemekx0y10 = new JButton(obrazekpozemku);
    public static JButton pozemekx1y10 = new JButton(obrazekpozemku);
    public static JButton pozemekx2y10 = new JButton(obrazekpozemku);
    public static JButton pozemekx3y10 = new JButton(obrazekpozemku);
    public static JButton pozemekx4y10 = new JButton(obrazekpozemku);
    public static JButton pozemekx5y10 = new JButton(obrazekpozemku);
    public static JButton pozemekx6y10 = new JButton(obrazekpozemku);
    public static JButton pozemekx7y10 = new JButton(obrazekpozemku);
    public static JButton pozemekx8y10 = new JButton(obrazekpozemku);
    public static JButton pozemekx9y10 = new JButton(obrazekpozemku);
    public static JButton pozemekx0y11 = new JButton(obrazekpozemku);
    public static JButton pozemekx1y11 = new JButton(obrazekpozemku);
    public static JButton pozemekx2y11 = new JButton(obrazekpozemku);
    public static JButton pozemekx3y11 = new JButton(obrazekpozemku);
    public static JButton pozemekx4y11 = new JButton(obrazekpozemku);
    public static JButton pozemekx5y11 = new JButton(obrazekpozemku);
    public static JButton pozemekx6y11 = new JButton(obrazekpozemku);
    public static JButton pozemekx7y11 = new JButton(obrazekpozemku);
    public static JButton pozemekx8y11 = new JButton(obrazekpozemku);
    public static JButton pozemekx9y11 = new JButton(obrazekpozemku);
    public static JButton pozemekx0y12 = new JButton(obrazekpozemku);
    public static JButton pozemekx1y12 = new JButton(obrazekpozemku);
    public static JButton pozemekx2y12 = new JButton(obrazekpozemku);
    public static JButton pozemekx3y12 = new JButton(obrazekpozemku);
    public static JButton pozemekx4y12 = new JButton(obrazekpozemku);
    public static JButton pozemekx5y12 = new JButton(obrazekpozemku);
    public static JButton pozemekx6y12 = new JButton(obrazekpozemku);
    public static JButton pozemekx7y12 = new JButton(obrazekpozemku);
    public static JButton pozemekx8y12 = new JButton(obrazekpozemku);
    public static JButton pozemekx9y12 = new JButton(obrazekpozemku);
    public static JButton pozemekx0y13 = new JButton(obrazekpozemku);
    public static JButton pozemekx1y13 = new JButton(obrazekpozemku);
    public static JButton pozemekx2y13 = new JButton(obrazekpozemku);
    public static JButton pozemekx3y13 = new JButton(obrazekpozemku);
    public static JButton pozemekx4y13 = new JButton(obrazekpozemku);
    public static JButton pozemekx5y13 = new JButton(obrazekpozemku);
    public static JButton pozemekx6y13 = new JButton(obrazekpozemku);
    public static JButton pozemekx7y13 = new JButton(obrazekpozemku);
    public static JButton pozemekx8y13 = new JButton(obrazekpozemku);
    public static JButton pozemekx9y13 = new JButton(obrazekpozemku);
    
    public static JLabel cesta = new JLabel(obrazekcesty);
    public static JLabel dum = new JLabel(obrazekdomu);
    public static JLabel uhelnydul = new JLabel(obrazekuhelnehodolu);
    public static JLabel nacitacipozadi = new JLabel(obrazeknacitacihopozadi);
    public static String[] infooapce = {"---------","Autoï¿½i","---------","Vytvoï¿½il: Matï¿½j Mï¿½ca","\n","------------------------------","Zkopï¿½rovanï¿½ obrï¿½zky","------------------------------","    Dï¿½m: depositphotos.com","    Uhelnï¿½ dï¿½l: iconspng.com","    Pozemek: cz.wallpapers-fenix.eu","    Naï¿½ï¿½tacï¿½ pozadï¿½: starovekyegypt.net","    Ikona: ï¿½T edu(edu.ceskatelevize.cz)","    Ikona mince: depositphotos.com"};
    public static JLabel verze = new JLabel("verze 1.2 beta");
    public static JLabel napis = new JLabel("Hra zaï¿½ne za:");
    public static JLabel ukazatelpenez;
    public static JLabel invDum;
    public static JLabel invCesta;
    public static JLabel invUhelnydul;
    
    public static JProgressBar odpocet = new JProgressBar(0, 5000);
    
    public static main.TownBuild tb = new main.TownBuild();
    
    public static void InitWindow() {
        okno.setTitle("Town build");
        okno.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        okno.addWindowListener(tb);
        okno.setVisible(true);
        okno.setLocation(500, 100);
        okno.setIconImage(new ImageIcon("ikona_new.png").getImage());
    }
    
    public static void InitLoadingGUI() {
        SwingUtilities.invokeLater(() -> {
            okno.setSize(700, 500);
            hrat.setVisible(true);
            okno.add(hrat);
            hrat.addActionListener(tb);
            hrat.setFocusable(false);
            hrat.setBorder(BorderFactory.createEtchedBorder());
            okno.add(nacitacipozadi);
            nacitacipozadi.setSize(700, 500);
            hrat.setLocation(350, 250);
            hrat.setEnabled(true);
            nacitacipozadi.add(hrat);
            nacitacipozadi.add(verze);
            hrat.setBackground(Color.YELLOW);
            hrat.setSize(100, 50);
            hrat.setFont(new Font("Consolas", Font.BOLD, 30));
            verze.setBounds(560, 430, 200, 20);
            verze.setFont(new Font("Consolas", Font.BOLD, 20));
            verze.setVisible(true);
        });
    }
    
    public void InitMainGUI() {
        okno.add(moznosti, BorderLayout.PAGE_END);
            okno.getContentPane().setBackground(Color.GREEN);
            moznosti.setBackground(Color.green);
            moznosti.add(obchod);
            moznosti.add(mesto);
            moznosti.add(inventar);
            moznosti.add(nastaveni);
            moznosti.add(ziskatpenize);
        
            mesto.setVisible(true);
            mesto.setFont(new Font("Consolas", Font.BOLD, 20));
            mesto.setEnabled(true);
            mesto.setBackground(Color.yellow);
            mesto.setFocusable(true);
            mesto.setBorder(BorderFactory.createEmptyBorder());
            mesto.addActionListener(tb);
            
            obchod.setVisible(true);
            obchod.setFont(new Font("Consolas", Font.BOLD, 20));
            obchod.setEnabled(true);
            obchod.setBackground(Color.yellow);
            obchod.setFocusable(true);
            obchod.setBorder(BorderFactory.createEmptyBorder());
            obchod.addActionListener(tb);
            
            inventar.setVisible(true);
            inventar.setFont(new Font("Consolas", Font.BOLD, 20));
            inventar.setEnabled(true);
            inventar.setBackground(Color.yellow);
            inventar.setFocusable(true);
            inventar.setBorder(BorderFactory.createEmptyBorder());
            inventar.addActionListener(tb);
            
            nastaveni.setVisible(true);
            nastaveni.setFont(new Font("Consolas", Font.BOLD, 20));
            nastaveni.setEnabled(true);
            nastaveni.setBackground(Color.yellow);
            nastaveni.setFocusable(true);
            nastaveni.setBorder(BorderFactory.createEmptyBorder());
            nastaveni.addActionListener(tb);
            
            ziskatpenize.setVisible(true);
            ziskatpenize.setFont(new Font("Consolas", Font.BOLD, 20));
            ziskatpenize.setEnabled(true);
            ziskatpenize.setBackground(Color.yellow);
            ziskatpenize.setFocusable(true);
            ziskatpenize.setBorder(BorderFactory.createEmptyBorder());
            ziskatpenize.addActionListener(tb);
            
            tb.mince_str = Long.toString(tb.mince);
            ukazatelpenez = new JLabel(tb.mince_str);
            ukazatelpenez.setFont(new Font("Consolas", Font.BOLD, 30));
            ukazatelpenez.setBackground(null);
            ukazatelpenez.setBorder(BorderFactory.createEmptyBorder());
            ukazatelpenez.setVisible(true);
            ukazatelpenez.setIcon(new ImageIcon("mince.png"));
            
            koupitcestu.setBorder(BorderFactory.createEtchedBorder());
            koupitcestu.setFocusable(false);
            koupitcestu.setVisible(true);
            koupitcestu.setBackground(Color.yellow);
            koupitcestu.setEnabled(true);
            koupitcestu.setFont(new Font("Consolas", Font.BOLD, 20));
            koupitcestu.addActionListener(tb);
                
            koupitdum.setBorder(BorderFactory.createEtchedBorder());
            koupitdum.setFocusable(false);
            koupitdum.setVisible(true);
            koupitdum.setBackground(Color.yellow);
            koupitdum.setEnabled(true);
            koupitdum.setFont(new Font("Consolas", Font.BOLD, 20));
            koupitdum.addActionListener(tb);
                
            koupituhelnydul.setBorder(BorderFactory.createEtchedBorder());
            koupituhelnydul.setFocusable(false);
            koupituhelnydul.setVisible(true);
            koupituhelnydul.setBackground(Color.yellow);
            koupituhelnydul.setEnabled(true);
            koupituhelnydul.setFont(new Font("Consolas", Font.BOLD, 20));
            koupituhelnydul.addActionListener(tb);
                
            buypanel.setVisible(true);
            buypanel.add(uhelnydul, BorderLayout.NORTH);
            buypanel.add(cesta, BorderLayout.NORTH);
            buypanel.add(dum, BorderLayout.NORTH);
            buypanel.add(koupituhelnydul, BorderLayout.SOUTH);
            buypanel.add(koupitcestu, BorderLayout.SOUTH);
            buypanel.add(koupitdum, BorderLayout.SOUTH);
            buypanel.setBackground(Color.GREEN);
            buypanel.setLayout(new GridLayout(2, 3));
            
            okno.getContentPane().add(ukazatelpenez, BorderLayout.NORTH);
            okno.add(buypanel);
            
            invUhelnydul = new JLabel("Uhelnï¿½doly:"+Integer.toString(tb.pocetuhelnychdolu));
            invCesta = new JLabel("Cesty:"+Integer.toString(tb.pocetcest));
            invDum = new JLabel("Domy:"+Integer.toString(+tb.pocetdomu));
            invUhelnydul.addMouseListener(tb);
            invCesta.addMouseListener(tb);
            invDum.addMouseListener(tb);
            listveci.setVisible(false);
            listveci.add(invUhelnydul);
            listveci.add(invDum);
            listveci.add(invCesta);
            listveci.setBackground(Color.green);
            listveci.setLayout(new GridLayout(3, 1));
            
            jaksepise.setBorder(BorderFactory.createEtchedBorder());
            jaksepise.setFocusable(false);
            jaksepise.setBackground(Color.yellow);
            jaksepise.setEnabled(true);
            jaksepise.setFont(new Font("Consolas", Font.BOLD, 20));
            jaksepise.addActionListener(tb);
            jaksepise.setBounds(690,490,100,50);
            
            napis.setFont(new Font("Consolas", Font.BOLD, 50));
            napis.setBounds(0, 150, 700, 60);
            okno.setFocusable(true);
            okno.addKeyListener(tb);
            
            odpocet.setForeground(Color.YELLOW);
            odpocet.setBackground(Color.red);
            odpocet.setValue(0);
            odpocet.setStringPainted(false);
            odpocet.setBounds(50, 350 , 600, 50);
            odpocet.setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, Color.BLUE));
            
            hernipole.setBackground(Color.GREEN);
            hernipole.add(odpocet);
            hernipole.add(napis);
    }
    
    /**
     * Definuje møížku a poté zavolá funkci tb.getDefaultIcon()
     */
    public static void mrizkainit() { 
        pozemekx0y0.addActionListener(tb);
        pozemekx1y0.addActionListener(tb);
        pozemekx2y0.addActionListener(tb);
        pozemekx3y0.addActionListener(tb);
        pozemekx4y0.addActionListener(tb);
        pozemekx5y0.addActionListener(tb);
        pozemekx6y0.addActionListener(tb);
        pozemekx7y0.addActionListener(tb);
        pozemekx8y0.addActionListener(tb);
        pozemekx9y0.addActionListener(tb);
        pozemekx0y1.addActionListener(tb);
        pozemekx1y1.addActionListener(tb);
        pozemekx2y1.addActionListener(tb);
        pozemekx3y1.addActionListener(tb);
        pozemekx4y1.addActionListener(tb);
        pozemekx5y1.addActionListener(tb);
        pozemekx6y1.addActionListener(tb);
        pozemekx7y1.addActionListener(tb);
        pozemekx8y1.addActionListener(tb);
        pozemekx9y1.addActionListener(tb);
        pozemekx0y2.addActionListener(tb);
        pozemekx1y2.addActionListener(tb);
        pozemekx2y2.addActionListener(tb);
        pozemekx3y2.addActionListener(tb);
        pozemekx4y2.addActionListener(tb);
        pozemekx5y2.addActionListener(tb);
        pozemekx6y2.addActionListener(tb);
        pozemekx7y2.addActionListener(tb);
        pozemekx8y2.addActionListener(tb);
        pozemekx9y2.addActionListener(tb);
        pozemekx0y3.addActionListener(tb);
        pozemekx1y3.addActionListener(tb);
        pozemekx2y3.addActionListener(tb);
        pozemekx3y3.addActionListener(tb);
        pozemekx4y3.addActionListener(tb);
        pozemekx5y3.addActionListener(tb);
        pozemekx6y3.addActionListener(tb);
        pozemekx7y3.addActionListener(tb);
        pozemekx8y3.addActionListener(tb);
        pozemekx9y3.addActionListener(tb);
        pozemekx0y4.addActionListener(tb);
        pozemekx1y4.addActionListener(tb);
        pozemekx2y4.addActionListener(tb);
        pozemekx3y4.addActionListener(tb);
        pozemekx4y4.addActionListener(tb);
        pozemekx5y4.addActionListener(tb);
        pozemekx6y4.addActionListener(tb);
        pozemekx7y4.addActionListener(tb);
        pozemekx8y4.addActionListener(tb);
        pozemekx9y4.addActionListener(tb);
        pozemekx0y5.addActionListener(tb);
        pozemekx1y5.addActionListener(tb);
        pozemekx2y5.addActionListener(tb);
        pozemekx3y5.addActionListener(tb);
        pozemekx4y5.addActionListener(tb);
        pozemekx5y5.addActionListener(tb);
        pozemekx6y5.addActionListener(tb);
        pozemekx7y5.addActionListener(tb);
        pozemekx8y5.addActionListener(tb);
        pozemekx9y5.addActionListener(tb);
        pozemekx0y6.addActionListener(tb);
        pozemekx1y6.addActionListener(tb);
        pozemekx2y6.addActionListener(tb);
        pozemekx3y6.addActionListener(tb);
        pozemekx4y6.addActionListener(tb);
        pozemekx5y6.addActionListener(tb);
        pozemekx6y6.addActionListener(tb);
        pozemekx7y6.addActionListener(tb);
        pozemekx8y6.addActionListener(tb);
        pozemekx9y6.addActionListener(tb);
        pozemekx0y7.addActionListener(tb);
        pozemekx1y7.addActionListener(tb);
        pozemekx2y7.addActionListener(tb);
        pozemekx3y7.addActionListener(tb);
        pozemekx4y7.addActionListener(tb);
        pozemekx5y7.addActionListener(tb);
        pozemekx6y7.addActionListener(tb);
        pozemekx7y7.addActionListener(tb);
        pozemekx8y7.addActionListener(tb);
        pozemekx9y7.addActionListener(tb);
        pozemekx0y8.addActionListener(tb);
        pozemekx1y8.addActionListener(tb);
        pozemekx2y8.addActionListener(tb);
        pozemekx3y8.addActionListener(tb);
        pozemekx4y8.addActionListener(tb);
        pozemekx5y8.addActionListener(tb);
        pozemekx6y8.addActionListener(tb);
        pozemekx7y8.addActionListener(tb);
        pozemekx8y8.addActionListener(tb);
        pozemekx9y8.addActionListener(tb);
        pozemekx0y9.addActionListener(tb);
        pozemekx1y9.addActionListener(tb);
        pozemekx2y9.addActionListener(tb);
        pozemekx3y9.addActionListener(tb);
        pozemekx4y9.addActionListener(tb);
        pozemekx5y9.addActionListener(tb);
        pozemekx6y9.addActionListener(tb);
        pozemekx7y9.addActionListener(tb);
        pozemekx8y9.addActionListener(tb);
        pozemekx9y9.addActionListener(tb);
        pozemekx0y10.addActionListener(tb);
        pozemekx1y10.addActionListener(tb);
        pozemekx2y10.addActionListener(tb);
        pozemekx3y10.addActionListener(tb);
        pozemekx4y10.addActionListener(tb);
        pozemekx5y10.addActionListener(tb);
        pozemekx6y10.addActionListener(tb);
        pozemekx7y10.addActionListener(tb);
        pozemekx8y10.addActionListener(tb);
        pozemekx9y10.addActionListener(tb);
        pozemekx0y11.addActionListener(tb);
        pozemekx1y11.addActionListener(tb);
        pozemekx2y11.addActionListener(tb);
        pozemekx3y11.addActionListener(tb);
        pozemekx4y11.addActionListener(tb);
        pozemekx5y11.addActionListener(tb);
        pozemekx6y11.addActionListener(tb);
        pozemekx7y11.addActionListener(tb);
        pozemekx8y11.addActionListener(tb);
        pozemekx9y11.addActionListener(tb);
        pozemekx0y12.addActionListener(tb);
        pozemekx1y12.addActionListener(tb);
        pozemekx2y12.addActionListener(tb);
        pozemekx3y12.addActionListener(tb);
        pozemekx4y12.addActionListener(tb);
        pozemekx5y12.addActionListener(tb);
        pozemekx6y12.addActionListener(tb);
        pozemekx7y12.addActionListener(tb);
        pozemekx8y12.addActionListener(tb);
        pozemekx9y12.addActionListener(tb);
        pozemekx0y13.addActionListener(tb);
        pozemekx1y13.addActionListener(tb);
        pozemekx2y13.addActionListener(tb);
        pozemekx3y13.addActionListener(tb);
        pozemekx4y13.addActionListener(tb);
        pozemekx5y13.addActionListener(tb);
        pozemekx6y13.addActionListener(tb);
        pozemekx7y13.addActionListener(tb);
        pozemekx8y13.addActionListener(tb);
        pozemekx9y13.addActionListener(tb);
        mrizka.add(pozemekx0y0);
        mrizka.add(pozemekx1y0);
        mrizka.add(pozemekx2y0);
        mrizka.add(pozemekx3y0);
        mrizka.add(pozemekx4y0);
        mrizka.add(pozemekx5y0);
        mrizka.add(pozemekx6y0);
        mrizka.add(pozemekx7y0);
        mrizka.add(pozemekx8y0);
        mrizka.add(pozemekx9y0);
        mrizka.add(pozemekx0y1);
        mrizka.add(pozemekx1y1);
        mrizka.add(pozemekx2y1);
        mrizka.add(pozemekx3y1);
        mrizka.add(pozemekx4y1);
        mrizka.add(pozemekx5y1);
        mrizka.add(pozemekx6y1);
        mrizka.add(pozemekx7y1);
        mrizka.add(pozemekx8y1);
        mrizka.add(pozemekx9y1);
        mrizka.add(pozemekx0y2);
        mrizka.add(pozemekx1y2);
        mrizka.add(pozemekx2y2);
        mrizka.add(pozemekx3y2);
        mrizka.add(pozemekx4y2);
        mrizka.add(pozemekx5y2);
        mrizka.add(pozemekx6y2);
        mrizka.add(pozemekx7y2);
        mrizka.add(pozemekx8y2);
        mrizka.add(pozemekx9y2);
        mrizka.add(pozemekx0y3);
        mrizka.add(pozemekx1y3);
        mrizka.add(pozemekx2y3);
        mrizka.add(pozemekx3y3);
        mrizka.add(pozemekx4y3);
        mrizka.add(pozemekx5y3);
        mrizka.add(pozemekx6y3);
        mrizka.add(pozemekx7y3);
        mrizka.add(pozemekx8y3);
        mrizka.add(pozemekx9y3);
        mrizka.add(pozemekx0y4);
        mrizka.add(pozemekx1y4);
        mrizka.add(pozemekx2y4);
        mrizka.add(pozemekx3y4);
        mrizka.add(pozemekx4y4);
        mrizka.add(pozemekx5y4);
        mrizka.add(pozemekx6y4);
        mrizka.add(pozemekx7y4);
        mrizka.add(pozemekx8y4);
        mrizka.add(pozemekx9y4);
        mrizka.add(pozemekx0y5);
        mrizka.add(pozemekx1y5);
        mrizka.add(pozemekx2y5);
        mrizka.add(pozemekx3y5);
        mrizka.add(pozemekx4y5);
        mrizka.add(pozemekx5y5);
        mrizka.add(pozemekx6y5);
        mrizka.add(pozemekx7y5);
        mrizka.add(pozemekx8y5);
        mrizka.add(pozemekx9y5);
        mrizka.add(pozemekx0y6);
        mrizka.add(pozemekx1y6);
        mrizka.add(pozemekx2y6);
        mrizka.add(pozemekx3y6);
        mrizka.add(pozemekx4y6);
        mrizka.add(pozemekx5y6);
        mrizka.add(pozemekx6y6);
        mrizka.add(pozemekx7y6);
        mrizka.add(pozemekx8y6);
        mrizka.add(pozemekx9y6);
        mrizka.add(pozemekx0y7);
        mrizka.add(pozemekx1y7);
        mrizka.add(pozemekx2y7);
        mrizka.add(pozemekx3y7);
        mrizka.add(pozemekx4y7);
        mrizka.add(pozemekx5y7);
        mrizka.add(pozemekx6y7);
        mrizka.add(pozemekx7y7);
        mrizka.add(pozemekx8y7);
        mrizka.add(pozemekx9y7);
        mrizka.add(pozemekx0y8);
        mrizka.add(pozemekx1y8);
        mrizka.add(pozemekx2y8);
        mrizka.add(pozemekx3y8);
        mrizka.add(pozemekx4y8);
        mrizka.add(pozemekx5y8);
        mrizka.add(pozemekx6y8);
        mrizka.add(pozemekx7y8);
        mrizka.add(pozemekx8y8);
        mrizka.add(pozemekx9y8);
        mrizka.add(pozemekx0y9);
        mrizka.add(pozemekx1y9);
        mrizka.add(pozemekx2y9);
        mrizka.add(pozemekx3y9);
        mrizka.add(pozemekx4y9);
        mrizka.add(pozemekx5y9);
        mrizka.add(pozemekx6y9);
        mrizka.add(pozemekx7y9);
        mrizka.add(pozemekx8y9);
        mrizka.add(pozemekx9y9);
        mrizka.add(pozemekx0y10);
        mrizka.add(pozemekx1y10);
        mrizka.add(pozemekx2y10);
        mrizka.add(pozemekx3y10);
        mrizka.add(pozemekx4y10);
        mrizka.add(pozemekx5y10);
        mrizka.add(pozemekx6y10);
        mrizka.add(pozemekx7y10);
        mrizka.add(pozemekx8y10);
        mrizka.add(pozemekx9y10);
        mrizka.add(pozemekx0y11);
        mrizka.add(pozemekx1y11);
        mrizka.add(pozemekx2y11);
        mrizka.add(pozemekx3y11);
        mrizka.add(pozemekx4y11);
        mrizka.add(pozemekx5y11);
        mrizka.add(pozemekx6y11);
        mrizka.add(pozemekx7y11);
        mrizka.add(pozemekx8y11);
        mrizka.add(pozemekx9y11);
        mrizka.add(pozemekx0y12);
        mrizka.add(pozemekx1y12);
        mrizka.add(pozemekx2y12);
        mrizka.add(pozemekx3y12);
        mrizka.add(pozemekx4y12);
        mrizka.add(pozemekx5y12);
        mrizka.add(pozemekx6y12);
        mrizka.add(pozemekx7y12);
        mrizka.add(pozemekx8y12);
        mrizka.add(pozemekx9y12);
        mrizka.add(pozemekx0y13);
        mrizka.add(pozemekx1y13);
        mrizka.add(pozemekx2y13);
        mrizka.add(pozemekx3y13);
        mrizka.add(pozemekx4y13);
        mrizka.add(pozemekx5y13);
        mrizka.add(pozemekx6y13);
        mrizka.add(pozemekx7y13);
        mrizka.add(pozemekx8y13);
        mrizka.add(pozemekx9y13);
        mrizka.setLayout(new GridLayout(10, 14));      
        mrizka.setBackground(Color.green);
        tb.getDefaultIcon();
    }
}